control_stock/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import home

urlpatterns = [
    path('', home, name='home'),
    path('produtos/', include('product.urls')),
    path('estoque/', include('stock.urls')),
    path('admin/', admin.site.urls),
]

product/urls.py
from product.forms import ProductForm
from django.urls import path
from product import views as view

app_name='product'

urlpatterns=[
    path('', view.product_list, name='product_list'),
    path('<int:pk>/', view.product_detail, name='product_detail'),
    path('add/', view.ProductCreate.as_view(), name='product_add'),
    path('<int:pk>/edit', view.ProductUpdate.as_view(), name='product_edit'),
]

stock/urls.py
from django.urls import path
from stock import views as view

app_name = 'stock'

urlpatterns = [
    path('', view.stock_entry_list, name='stock_entry_list'),
    path('detalhe-estoque/<int:pk>/', view.stock_entry_detail, name='stock_entry_detail'), 
    path('add/', view.stock_entry_add, name='stock_entry_add'),
]

core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'create_at',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modified_at',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

product/models.py
from django.db import models
from django.urls import reverse_lazy


class Product(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('estoque Atual')
    estoque_minimo = models.PositiveIntegerField('estoque minimo', default=0)

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('product:product_detail', kwargs={'pk': self.pk})

stock/models.py
from django.contrib.auth.models import User
from django.db import models
from core.models import TimeStampedModel
from product.models import Product

MOVIMENT = (
    ('e', 'entrada'),
    ('s', 'saída'),
)

class Stock(TimeStampedModel):
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE)
    nf = models.PositiveIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENT)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.pk} - {self.nf} - {self.created.strftime("%d/%m/%Y")}'

    def nf_format(self):
        return str(self.nf).zfill(3)


class StockItems(models.Model):
    estoque = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='estoques')
    produto = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField()

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return f'{self.pk} - {self.estoque.pk} - {self.produto}'

product/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

stock/forms.py
from django import forms
from .models import Stock, StockItems


class StockForm(forms.ModelForm):

    class Meta:
        model = Stock
        fields = '__all__'


class StockItemsForm(forms.ModelForm):

    class Meta:
        model = StockItems
        fields = '__all__'

core/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'index.html')

product/views.py
from django.views.generic import CreateView, UpdateView
from django.shortcuts import render
from product.models import Product
from .forms import ProductForm


def product_list(request):
    template_name = 'product_list.html'
    products = Product.objects.all()
    context = {'products': products}
    return render(request, template_name, context)


def product_detail(request, pk):
    template_name = 'product_detail.html'
    product = Product.objects.get(pk=pk)
    context = {'product': product}
    return render(request, template_name, context)

class ProductCreate(CreateView):
    model = Product
    template_name = 'product_form.html'
    form_class = ProductForm
    
class ProductUpdate(UpdateView):
    model = Product
    template_name = 'product_form.html'
    form_class = ProductForm

stock/views.py
from stock.forms import StockForm, StockItemsForm
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url
from .models import Stock, StockItems



def stock_entry_list(request):
    template_name = 'stock_entry_list.html'
    stocks = Stock.objects.filter(movimento='e')
    context = {
        'stocks': stocks
    }
    return render(request, template_name, context)


def stock_entry_detail(request, pk):
    template_name = 'stock_entry_detail.html'
    stock = Stock.objects.get(pk=pk)
    context = {
        'stock': stock

    }
    return render(request, template_name, context)


def stock_entry_add(request):
    template_name = 'stock_entry_form.html'
    stock_form=Stock()
    stock_item_formset = inlineformset_factory(
        Stock,
        StockItems,
        form=StockItemsForm,
        extra=0,
        min_num=1,
        validate_min=True,
    )
    if request.method == 'POST':
        form = StockForm(request.POST, instance=stock_form, prefix='main')
        formset = stock_item_formset(
            request.POST,
            instance=stock_form,
            prefix='stock'
        )
        if form.is_valid() and formset.is_valid():
            form=form.save()
            formset.save()
            url = 'stock:stock_entry_detail'
            return HttpResponseRedirect(resolve_url(url, form.pk))
    else:
        form = StockForm(instance=stock_form, prefix='main')
        formset = stock_item_formset(instance=stock_form, prefix='stock')

    context = {'form': form, 'formset': formset}
    return render(request, template_name, context)

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico" type="image/x-icon">

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css%}{% endblock css %}
    <title>Estoque</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'home' %}">Estoque</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'product:product_list' %}">Produtos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Estoque
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'stock:stock_entry_list' %}">Entrada</a>
                  <a class="dropdown-item" href="#">Saída</a>
                </div>
              </li>
            
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Produto" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisa</button>
          </form>
        </div>
      </nav>
    <div class="container">
      {% block content %} {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    {% block js %} {% endblock %}
  </body>
</html>

core/templates/index.html
{% extends "base.html" %}

{% block content %}

<h1>Hello world!</h1>
{% endblock content %}

product/templates/product_detail.html
{% extends "base.html" %} {% block content %}
<a href="{% url 'product:product_list' %}">Voltar</a>
<h3>
  {{ product }}
  <span class="pull-right"
    ><a href="{% url 'product:product_edit' product.pk %}"
      ><button class="btn btn-success">
        <span class="fa fa-pencil"></span>Editar</button></a
  ></span>
</h3>
<div class="col-sm-6 mt-4">
    <table class="table table-user-information">
        <tbody><tr>
            <th class="text-right">Importado</th>
            <td>
                {% if product.importado %}
          <i class="fa fa-check-circle ok"></i>
          {% else %}
          <i class="fa fa-minus-circle no"></i>
          {% endif %}
            </td>
        </tr>
        <tr>
            <th class="text-right">NCM</th>
            <td>{{ product.ncm }}</td>
        </tr>
        <tr>
            <th class="text-right">Preço</th>
            <td>R$ {{ product.preco }}</td>
        </tr>
        <tr>
            <th class="text-right">Estoque</th>
            <td>{{ product.estoque }}</td>
        </tr>
        <tr>
            <th class="text-right">Estoque mínimo</th>
            <td>{{ product.estoque_minimo }}</td>
        </tr>

        </tbody>
    </table>
</div>
{% endblock %}

product/templates/product_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block css %}
<style>
    span.required:after {
        content: "*";
        color: red;
    }
</style>
{% endblock %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for field in form.visible_fields %}
    <div class="form-group{% if field.erros %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}"></label>
        {% if field.field.required %}
        <span class="required">{{ field.label }} </span>
    {% else %}
    {{ field.label}}
    {% endif %}
    </label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
    <span class="text-muted">{{ error }}</span>
    {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
{% endblock %}

product/templates/product_list.html
{% extends "base.html" %} {% block content %}
<div class="page-header">
  <h2>Lista de Produtos
      <span class="pull-right">
          <a href="{% url 'product:product_add' %}">
          <button type="button" class="btn btn-primary">
              <span class="fa fa-plus"></span>
              Adicionar
        </button>
    </a>
    </span>
  </h2>
  {% if products %}
  <table class="table table-striped mt-4">
    <thead>
      <tr>
        <th>Importado</th>
        <th>NCM</th>
        <th>Produto</th>
        <th>Preço</th>
        <th class="text-center">Estoque</th>
        <th class="text-center">Estoque mínimo</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
      <tr>
        <td>
          {% if product.importado %}
          <i class="fa fa-check-circle ok"></i>
          {% else %}
          <i class="fa fa-minus-circle no"></i>
          {% endif %}
        </td>
        <td>{{ product.ncm }}</td>
        <td><a href="{% url 'product:product_detail' product.pk%}">
            {{ product.produto }}
        </td>
        </a>
        <td>R$ <span class="">{{ product.preco }}</span></td>
        <td class="text-center">{{ product.estoque}}</td>
        <td class="text-center">{{ product.estoque_minimo }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <div class="alert alert-warning text-center">
    Nenhum produto cadastrado!
  </div>
  {% endif %}
</div>
{% endblock %}

stock/templates/stock_entry_detail.html
{% extends "base.html" %} {% block content %}
<a href="{% url 'stock:stock_entry_list' %}">Voltar</a>
<h3>
  {{ stock }}
  <span class="pull-right"
    ><a href="{% url 'stock:stock_entry_detail' stock.pk %}"
      ><button class="btn btn-success">
        <span class="fa fa-pencil"></span>Editar</button></a
  ></span>
</h3>
<div class="col-sm-6 mt-4">
    <table class="table table-user-information">
        <tbody>
        <tr>
            <th class="text-right">Item</th>
            <td>{{ stock }}</td>
        </tr>
        <tr>
            <th class="text-right">NF</th>
            <td>{{ stock.nf }}</td>
        </tr>
        <tr>
            <th class="text-right">Funcionário</th>
            <td>{{ stock.funcionario }}</td>
        </tr>
        </tbody>
    </table>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Produto</th>
      <th>Quantidade</th>
      <th>Saldo</th>
    </tr>
  </thead>
  <tbody>
    {% for stock in stock.estoques.all %}
      <tr>
        <td>{{ stock.produto }}</td>
        <td>{{ stock.quantidade }}</td>
        <td>{{ stock.saldo }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

stock/templates/stock_entry_form.html
{% extends "base.html" %} {% load widget_tweaks %} {% load bootstrap %} 

{% block css %}
<style>
    span.required:after {
        content: "*";
        color: red;
    }
</style>
{% endblock %}

{% block content %}
<a href="{% url 'stock:stock_entry_list' %}">Voltar</a>
<div class="row">
    <div class="cols">
      <form method="POST" novalidate>
        {% csrf_token %}
        <legend style="border-bottom: 1px solid #e5e5e5;">Estoque Entrada</legend>
  
        <div class="row">
          <div class="col-sm-6">
            {% for field in form.visible_fields %}
              <div class="form-group{% if field.errors %} has-error {% endif%}">
                <label for="{{ field.id_for_label }}">
                  {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                  {% else %}
                    {{ field.label }}
                  {% endif %}
                </label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                  <span class="text-muted">{{ error }}</span>
                {% endfor %}
              </div>
            {% endfor %}
          {{ formset.management_form }}
          </div>
        </div>
  
        <div class="row">
          <div class="col-sm-12">
            <legend style="border-bottom: 1px solid #e5e5e5;">Produtos</legend>
            <div id="stock" class="form-inline">
              {% for stock_item_form in formset %}
                <div id="item-{{ forloop.counter0 }}" class="form-group">
                  {{ stock_item_form|bootstrap }}
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
  
        <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
          <i class="fa fa-plus"></i> Adicionar
        </span>
  
        <div class="row float-right">
          <div class="col-sm-12" style="margin-top: 10px;">
            <div class="form-inline buttons">
              <button class="btn btn-primary" value="Save">
                <i class="fa fa-floppy-o"></i>
                Salvar
              </button>
              <a href="{% url 'stock:stock_entry_list' %}" class="btn btn-danger">
                <i class="fa fa-times"></i>
                Cancelar
              </a>
            </div>
          </div>
        </div>
  
      </form>
    </div>
  </div>
  
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
    $('#add-item').click(function(event){
        event.preventDefault();
        let count = $('#stock').children().length;
        let tmpMarkup = $('#item-stock').html();
        let = compiled = tmpMarkup.replace(/__prefix__/g, count);
        $('div#stock').append(compiled);

        // update form count
        $('#id_stock-TOTAL_FORMS').attr('value', count + 1);

        // some animate to scrol the view form
        $('html, body').animate({
            scrollTop: $('#add-item').position.top - 200
        }, 800);
    });
});
</script>

<script type="text/html" id="item-stock">
    <div id="item-__prefix__" class="form-group" style="margin-top: 10px">
        {{ formset.empty_form|bootstrap }}
    </div>
</script>
{% endblock %}

stock/templates/stock_entry_list.html
{% extends "base.html" %}

{% block content %}
<h2>Lista de Estoque
    <span class="pull-right">
        <a href="{% url 'stock:stock_entry_add' %}">
        <button type="button" class="btn btn-primary">
            <span class="fa fa-plus"></span>
            Adicionar
      </button>
  </a>
  </span>
</h2>
{% if stocks %}
<table class="table table-striped mt-4">
    <thead>
        <tr>
            <th>Item</th>
            <th>NF</th>
            <th>Data</th>
            <th>Funcionário</th>
        </tr>
    </thead>
    <tbody>
        {% for stock in stocks %}
        <tr>
            <td><a href="{% url 'stock:stock_entry_detail' stock.pk %}">{{ stock }}</a></td>
            <td>{{ stock.nf_format }}</td>
            <td>{{ stock.created }}</td>
            <td>{{ stock.funcionario.first_name }}</td>
        </tr>

        {% endfor %}
    </tbody>
</table>
{% else %}
<div class="alert-alert warning text-center mt-4">
    Sem item na lista.
</div>
{% endif %}
{% endblock %}